In [0]:
#importações e instalações
!pip install tensorflow
import tensorflow as tf
tensorflow.__version__
import numpy as np

In [0]:
#somando dois valores constantes
valor1 = tf.constant(2)
valor2 = tf.constant(3)
soma= valor1 + valor2
with tf.Session() as sess:
  s = sess.run(soma)

#manipulando variaveis
valor3 = tf.constant(15, name = 'valor3')
valor4 = tf.constant(15, name = 'valor4')
soma1= valor3 + valor4
init= tf.global_variables_initializer()
with tf.Session() as sess:
  a = sess.run(soma1)

In [0]:
#manipulando vetores
vetor = tf.constant([5,10,15], name='vetor')
valor5 = tf.Variable(0, name = 'valor')

init2= tf.global_variables_initializer()
#--programação python normal mas com sessão
with tf.Session()as sess:
  sess.run(init2)
  for i in range(3):
    valor5= valor5+1
    print(sess.run(valor5))

#manipulação de matrizes
a1 = tf.constant([[1,2,3],[4,5,6]], name="a1")
b1 = tf.constant([[1,2,3],[4,5,6]], name="b1")
soma2 = tf.add(a1,b1)

with tf.Session()as sess:
  print(sess.run(soma2))

#multiplicação de matrizes
a2 = tf.constant([[1,2],[3,4]])
b2 = tf.constant([[-1,3],[4,2]])
multiplicacao = tf.matmul(a2,b2)

with tf.Session() as sess:
  print(sess.run(multiplicacao))


1
2
3
[[ 2  4  6]
 [ 8 10 12]]
[[ 7  7]
 [13 17]]


In [0]:
#produto escalar
entradas= tf.constant([[-1.0,7.0,5.0]], name = "entradas")
pesos = tf.constant([[0.8,0.1,0]], name = "pesos")
multiplic = tf.multiply(entradas,pesos)
with tf.Session() as sess:
  print(sess.run(somaFunc))
  somaFunc = tf.reduce_sum(multiplic)

-0.100000024


In [0]:
#placeholder
p= tf.placeholder('float', None)
operacao = p+2
with tf.Session() as sess:
  resultado = sess.run(operacao, feed_dict = {p:[1,2,3]})
  print(resultado)

  p2 = tf.placeholder('float', [None, 5])
  operacao2 = p2+5
  with tf.Session() as sess:
    dados = [[1,2,3,4,5],[6,7,8,9,10]]
    resultado = sess.run(operacao2, feed_dict = {p2:dados})
    print(resultado)

[3. 4. 5.]
[[ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


In [0]:
#grafos e tensorboard
tf.reset_default_graph()
a9= tf.add(2,2, name='add')
b9= tf.multiply(a9, 3, name="mult1")
c9= tf.multiply(b9, a9, name="mult2")

with tf.Session() as sess:
  writer = tf.summary.FileWriter('output', sess.graph)
  print(sess.run(c9))
  writer.close()

48
